version: '2'
services:
  golang:
    build: ./golang/
    image: golang-1.6:4
    volumes:
      - ../project:/app
    ports:
      - 19808:19808
    environment:
      - GOPATH=/app
      - BS_DB_PATH=/app
    command: sleep 90000000
