version: '2'
services:
  golang:
    build: ./golang/
    image: golang-1.6:4
    volumes:
      - ../project:/app
      - ../:/var/lib/bow
    ports:
      - 19808:19808
    cap_add:
      - SYS_ADMIN
    environment:
      - GOPATH=/app
    command: sleep 90000000
